### ISSUE TITLE
Opinión del CRUD

### ISSUE THREAD

**Issue by IngPaz** [IngPaz/laravel-trainee#1]
@ricalanis aquí un CRUD, bueno el comienzo, ya hace altas, bajas y modificaciones

**Comment by ricalanis** [comment]
Lo vi muy tarde! Mañana sin falta le doy una checada

**Comment by IngPaz** [comment]
ok gracias @ricalanis

**Comment by ricalanis** [comment]
¿Me lo asignas para que no se me pierda? (:
